connectionname:
  environmentname:
    dbhost:           ''
    dbname:           ''
    dbuser:           ''
    dbpassword:       ''
    local_dbuser:     ''
    local_dbname:     ''
    local_dbpassword: ''
    host:             ''
    user:             ''
    adapter:          ''